controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: false

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

    range_broad:
      type: range_sensor_broadcaster/RangeSensorBroadcaster

    gripper_cont:
      type: forward_command_controller/ForwardCommandController
    
diff_cont:
  ros__parameters:
    publish_rate: 30.0
    base_frame_id: base_link
    
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.135
    wheel_radius: 0.02175
    # Tuning params
    wheel_separation_multiplier: 1.02
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    use_stamped_vel: false
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.05
        min_velocity: -0.05
        has_acceleration_limits: true
        max_acceleration: 0.1
        min_acceleration: -0.1
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 0.5
        min_velocity: -0.5
        has_acceleration_limits: true
        max_acceleration: 1.0
        min_acceleration: -1.0

gripper_cont:
  ros__parameters:
    joints:
      - gripper_right_joint
    interface_name: effort


