controller_manager:
  ros__parameters:
    update_rate: 30
    use_sim_time: false

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster
    
diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: base_link
    
    left_wheel_names: ["left_wheel_joint"]
    right_wheel_names: ["right_wheel_joint"]
    wheel_separation: 0.135
    wheel_radius: 0.02175
    # Tuning params
    wheel_separation_multiplier: 1.0
    left_wheel_radius_multiplier: 1.0
    right_wheel_radius_multiplier: 1.0

    use_stamped_vel: false
    linear:
      x:
        has_velocity_limits: true
        max_velocity: 0.1
        min_velocity: -0.1
        has_acceleration_limits: true
        max_acceleration: 0.2
        min_acceleration: -0.2
    angular:
      z:
        has_velocity_limits: true
        max_velocity: 0.4
        min_velocity: -0.4
        has_acceleration_limits: true
        max_acceleration: 0.8
        min_acceleration: -0.8


