twist_mux:
  ros__parameters:
    topics:
      navigation:
        topic: cmd_vel
        timeout: 1.0
        priority: 10
      teleop:
        topic: cmd_vel_teleop
        timeout: 1.0
        priority: 100
      